salesforce:
  username: "dsahoo2@ncsu.edu.qa"
  password: "Dips@123d"
  securitytoken: "OQh3GFKlN1hcn3XyAAU386Ghg"
  
fileConnector:
  phoneRecordsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\PhoneRecords"
  phoneRecordsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\PhoneRecords"
  PhoneRecordsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\PhoneRecords\\PhoneRecordsFile.xlsx"
  PhoneRecordsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\PhoneRecords\\PhoneRecordsResults.csv"
  AddressRelationsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\AddressRelations"
  AddressRelationsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\AddressRelations"
  AddressRelationsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\AddressRelations\\AddressRelationsFile.xlsx"
  AddressRelationsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\AddressRelations\\AddressRelationsResults.csv"
  ConstituentsReadFolder: "C:\\Users\\disahoo\\Downloads\\MulesoftDataLoad\\CsvFiles\\Constituents"
  ConstituentsMoveToFolder: "C:\\Users\\disahoo\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Constituents"
  ConstituentsReadExcelFile: "C:\\Users\\disahoo\\Downloads\\MulesoftDataLoad\\CsvFiles\\Constituents\\ConstituentsFile.xlsx"
  ConstituentsWriteExcelFile: "C:\\Users\\disahoo\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Constituents\\ConstituentsResults.csv"