salesforce:
  username: "dsahoo2@ncsu.edu.ascenddev"
  password: "Dips@123dips"
  securitytoken: "e0WfOrpLxb8zadeUnnjKikzMj"
  
fileConnector:
  phoneRecordsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\PhoneRecords"
  phoneRecordsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\PhoneRecords"
  PhoneRecordsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\PhoneRecords\\PhoneRecordsFile.xlsx"
  PhoneRecordsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\PhoneRecords\\PhoneRecordsResults.csv"
  AddressRelationsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\AddressRelations"
  AddressRelationsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\AddressRelations"
  AddressRelationsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\AddressRelations\\AddressRelationsFile.xlsx"
  AddressRelationsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\AddressRelations\\AddressRelationsResults.csv"
  ConstituentsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\Constituents"
  ConstituentsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Constituents"
  ConstituentsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\Constituents\\ConstituentsFile.xlsx"
  ConstituentsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Constituents\\ConstituentsResults.csv"
  EmailsReadFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\Emails"
  EmailsMoveToFolder: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Emails"
  EmailsReadExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvFiles\\Emails\\EmailsFile.xlsx"
  EmailsWriteExcelFile: "C:\\Users\\dsahoo2\\Downloads\\MulesoftDataLoad\\CsvUploadResultFiles\\Emails\\EmailsResults.csv"